### ISSUE TITLE
request for ACDC dataset

### ISSUE THREAD

**Issue by xinnvY** [kathyliu579/CS-Unet#5]
could you share your source ACDC dataset and your preprocess code to me?or preprocessed ACDC dataset?   wyy2671@163.com 
Thanks!!!

**Comment by kathyliu579** [comment]
Hi 
this is our processed dataset. 
https://drive.google.com/drive/folders/1pSc1CRmmhO0e_2uk-U8fgDoOjy5Ye0-d?usp=sharing

If our work is useful to you, we hope to get your citation. Thank you so much！

**Comment by xinnvY** [comment]
> Hi this is our processed dataset. https://drive.google.com/drive/folders/1pSc1CRmmhO0e_2uk-U8fgDoOjy5Ye0-d?usp=sharing
> 
> If our work is useful to you, we hope to get your citation. Thank you so much！

thanks for your reply and sharing,i still have some doubts.
Did this data be preprocessed by the author of Transunet?maybe its critical for me because i want to use the same dataset as TranUnet for myself research!

**Comment by kathyliu579** [comment]
It is same original dataset, but as for preprocess, if you want the same preprocess, you'd better ask them for the precessed dataset?

From: xinnvY ***@***.***>
Date: Wednesday, September 20, 2023 at 08:10
To: kathyliu579/CS-Unet ***@***.***>
Cc: Qianying Liu (PGR) ***@***.***>, Comment ***@***.***>
Subject: Re: [kathyliu579/CS-Unet] request for ACDC dataset (Issue #5)

Hi this is our processed dataset. https://drive.google.com/drive/folders/1pSc1CRmmhO0e_2uk-U8fgDoOjy5Ye0-d?usp=sharing

If our work is useful to you, we hope to get your citation. Thank you so much！

thanks for your reply and sharing,i still have some doubts.
Did this data be preprocessed by the author of Transunet?maybe its critical for me because i want to use the same dataset as TranUnet for myself research!
